### ISSUE TITLE
How to use a slug field for the URL?

### ISSUE THREAD

**Issue by visualcookie** [Jonesus/gatsby-source-directus7#10]
Hey.

Right now when the post is created, the URL will be `/post/{id}/`. Is it somehow possible to use a slug field? I have one added as `title_slug` which is a mirror of the `title` field in my `Post` collection.

**Comment by Jonesus** [comment]
Hello!

I assume you're talking about an application built following the example in the README.md, which isn't technically a part of this package but just an example of how it could be used :sweat_smile: 

However assuming you've followed the example, if your `Post` items have a `title_slug` or some other field you want to use in the Directus side of things, you can edit the file `gatsby_node.js` line 23 by changing

```
const url = `post/${node.directusId}`;
```
to
```
const url = `post/${node.title_slug}`;
```
for example :)

**Comment by visualcookie** [comment]
Yeah, did that + added the field to the Graph query in `gatsby-node.js`. Worked out :)
