### ISSUE TITLE
Get related translations

### ISSUE THREAD

**Issue by visualcookie** [Jonesus/gatsby-source-directus7#12]
Hey.

I managed to set-up translations as described in the documentation of Directus. Now I'm not able to get this translated posts (e.g. in english or german) with the plugin.

Doc part to the setup: https://docs.directus.io/guides/relationships.html#translations

Is it not possible with this plugin?

**Comment by Jonesus** [comment]
It should be possible as under the hood it's not really that different from a standard relation and I feel like I've had it work before, unfortunately I might not have time to look at it before next week but at least then I'll try to come up with something

**Comment by visualcookie** [comment]
@Jonesus Nice. Yeah, I already tried to check GraphiQL, but could not find any query that could've done this.

**Comment by Jonesus** [comment]
Hi! I tried the same setup:

> Doc part to the setup: https://docs.directus.io/guides/relationships.html#translations

using the newest version of my plugin (0.7.1) and the newest version of Directus (App 7.5.0 and API 2.1.1) and it works flawlessly for me: 
![Screenshot from 2019-06-17 23-26-51](https://user-images.githubusercontent.com/16649390/59634426-6ee20800-9157-11e9-9e19-9b55f66c1d77.png)

Do you think you could give me your database dump again? I'd need all the set up collections and also the `directus_relations` -collection

**Comment by visualcookie** [comment]
Hey, sure!

[That dump](https://github.com/Jonesus/gatsby-source-directus7/files/3300142/tables_dump_18._June_2019.gz) should get you covered regarding my current setup.

**Comment by Jonesus** [comment]
Hey @visualcookie ! For some reason the dump you gave me was missing the `translations`-field in the `Posts`-collection as I would've expected it to have as following through the instructions given [here](https://docs.directus.io/guides/relationships.html#setup-4). After I set up the field in the `Posts` as follows:

![Screenshot from 2019-06-23 15-08-11](https://user-images.githubusercontent.com/16649390/59976119-d4574e00-95c8-11e9-8a9f-690186b70f30.png)
![Screenshot from 2019-06-23 15-08-20](https://user-images.githubusercontent.com/16649390/59976120-d7523e80-95c8-11e9-9408-f4cd8ffc3e92.png)
![Screenshot from 2019-06-23 15-08-33](https://user-images.githubusercontent.com/16649390/59976121-dae5c580-95c8-11e9-999e-9d667a835e95.png)

the translations show up in GraphiQL as they did on my test setup:

![Screenshot from 2019-06-23 15-09-36](https://user-images.githubusercontent.com/16649390/59976138-01a3fc00-95c9-11e9-9359-854030ba9e23.png)

I didn't try out the file problem yet but I'll try digging into that too. If this configuration fixes your translations issue then awesome, and if you can reproduce the file thingy and provide me with a database dump of that problem too it would make the process quite a bit faster for me :)

**Comment by visualcookie** [comment]
Finally had the time to continue. It's weird that I don't have the `translations` field for the query.

![image](https://user-images.githubusercontent.com/1857554/60492933-393b3400-9cac-11e9-987e-018e551844e0.png)

**Comment by visualcookie** [comment]
Here's the dump of the current set-up without the `jobs` and `teams` collection.

[directus.gz](https://github.com/Jonesus/gatsby-source-directus7/files/3349088/directus.gz)

**Comment by Jonesus** [comment]
Hey!

That one works for me out of the box too...

![Screenshot from 2019-07-02 19-27-17](https://user-images.githubusercontent.com/16649390/60529813-12a6e880-9d00-11e9-99a5-6ea7b597eef4.png)

And my `npm run start` output:
```
> gatsby-starter-default@0.1.0 develop /home/jonesus/code/gsd_dev
> gatsby develop

success open and validate gatsby-configs - 0.006 s
success load plugins - 0.394 s
success onPreInit - 0.008 s
success initialize cache - 0.023 s
success copy gatsby files - 0.021 s
success onPreBootstrap - 0.008 s
GSD7: info Started logging for gatsby-source-directus7.
GSD7: info Directus data fetcher initializing...
GSD7: info targetStatus is: draft
GSD7: success Connected to Directus!
GSD7: success Logged in to Directus!
GSD7: info Fetching Directus file data...
GSD7: success Found 0 files from Directus.
GSD7: info Downloading Directus files to Gatsby build cache...
GSD7: success Downloaded all 0 files from Directus!
GSD7: info Fetching Directus Collection data...
GSD7: info Fetching Directus Items data...
GSD7: info Status matched for languages 1. Using item
GSD7: info Status matched for languages 2. Using item
GSD7: info Status matched for articles 1. Using item
GSD7: info Status matched for article_translations 1. Using item
GSD7: info Status matched for article_translations 2. Using item
GSD7: info Fetching Directus Relations data...
GSD7: success Retrieved all data from Directus!
GSD7: info Directus data processing starting...
GSD7: info Mapping Directus relations to Items...
GSD7: info Found Many-To-One relation: team -> jobs
GSD7: warning Missing One-To-Many relation in 'team'. The relation
GSD7: warning will be called 'jobs' in GraphQL as a best guess.
GSD7: info Found Many-To-One relation: articles -> article_translations
GSD7: info Found One-To-Many relation: article_translations -> articles
GSD7: info Cleaning junction collections...
GSD7: info Mapping Directus files to Items...
GSD7: info Generating GraphQL nodes...
GSD7: success All done!
GSD7: info Ended logging for gatsby-source-directus7.
success source and transform nodes - 0.335 s
success building schema - 0.244 s
success createPages - 0.004 s
success createPagesStatefully - 0.043 s
success onPreExtractQueries - 0.005 s
success update schema - 0.033 s
success extract queries from components - 0.151 s
success write out requires - 0.005 s
success write out redirect data - 0.003 s
success Build manifest and related icons - 0.190 s
success onPostBootstrap - 0.204 s
⠀
info bootstrap finished - 3.581 s
⠀
success run static queries - 0.259 s — 3/3 12.15 queries/second
success run page queries - 0.078 s — 5/5 80.29 queries/second
success Generating image thumbnails — 6/6 - 0.435 s
 DONE  Compiled successfully in 4642ms
```

What versions of the packages are you running? My test config is gatsby-source-directus7 == 0.8.0, Gatsby == 2.10.0 and Directus suite == 190621A, I can't really figure out what's causing the disparity between our results...

**Comment by Jonesus** [comment]
Hey @visualcookie ! Could you paste your `gatsby-source-directus7` config from `gatsby-config.js`? It seems according to your build output that your target status filters out all the items in Directus according to these lines:

```
GSD7: warning No item of 1 in languages matched target status draft. This might lead to unexpected behavior!
GSD7: warning No item of 2 in languages matched target status draft. This might lead to unexpected behavior!
GSD7: warning No item of 1 in article_translations matched target status draft. This might lead to unexpected behavior!
```

So changing either the config's `targetStatus` / `defaultStatus` or changing the statuses of items should make the correct nodes appear in GraphQL!

**Comment by visualcookie** [comment]
Hey @Jonesus. Sure, the config looks as followed:

```javascript
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-flow`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/assets`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/assets/browser-icon.png`,
      },
    },
    {
      resolve: `gatsby-plugin-module-resolver`,
      options: {
        root: `./src`,
        aliases: {
          components: `./components`,
          constants: `./constants`,
          i18n: `./i18n`,
          pages: `./pages`,
          styles: `./styles`,
          utils: `./utils`,
          assets: `./assets`,
          sections: `./sections`,
          templates: `./templates`,
          static: {
            root: `./public`,
            alias: `./static`,
          },
        },
      },
    },
    {
      resolve: `gatsby-plugin-intl`,
      options: {
        path: `${__dirname}/src/i18n`,
        languages: [`en`, `de`],
        defaultLanguage: `de`,
        redirect: true,
      },
    },
    {
      resolve: `gatsby-source-directus7`,
      options: {
        url: 'XXX',
        project: '_',
        email: 'XXX',
        password: 'XXX',
        targetStatus: 'draft',
        defaultStatus: 'published',
      },
    },
  ],
}

```

**Comment by Jonesus** [comment]
That is interesting, I tried it with the same setup
```
targetStatus: 'draft',
defaultStatus: 'published',
```
And those work for me, the only way I managed to make it fail was with both of those being `'draft'`... Those fields aren't required, so if you try removing them completely from the config how does the build output look like then?

**Comment by visualcookie** [comment]
After removing the `targetStatus` and `defaultStatus` fields from the config and restarting with `yarn start`, it works without any errors and the `translations` field is now also included in `allDirectusArticle`.

**Comment by Jonesus** [comment]
Great, I can't really figure out why it wouldn't work for you with the settings enabled as I can't reproduce the issue on my end, but if you feel you can manage without those features lets roll with this 👍
