### ISSUE TITLE
Filter for articles with translations seems broke

### ISSUE THREAD

**Issue by visualcookie** [Jonesus/gatsby-source-directus7#15]
Hey.

When requesting an article with a translations filter, to only get e.g. `en`, it doesn't work. It still returns all articles.

```graphql
query {
  allDirectusArticle(filter: {translations: {elemMatch: {language: {eq: "en"}}}}) {
    edges {
      node {
        translations {
          title
          slug
          excerpt
          language
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "allDirectusArticle": {
      "edges": [
        {
          "node": {
            "translations": [
              {
                "title": "10 tips to manage your finances",
                "slug": "10-tips-to-manage-your-finances",
                "excerpt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qui est in parvis malis.",
                "language": "en"
              },
              {
                "title": "10 Tipps, wie Sie Ihre Finanzen verwalten können",
                "slug": "10-tipps-wie-sie-ihre-finanzen-verwalten-konnen",
                "excerpt": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Qui est in parvis malis.",
                "language": "de"
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by visualcookie** [comment]
@HashemKhalifa Sure, I did some hacky stuff for now.

```jsx
{articles.map(({ node }): React$Node => {
  // TODO: Remove it as soon as the filter function issue has been resolved
  const translatedArticle = node.translations.filter(
    a => a.language === intl.locale
  )

  return (
    <>
      {translatedArticle.map(article => (
        <Article
          tag={node.category}
          author={node.author}
          date={node.created_on}
          article={article}
        />
      ))}
    </>
  )
})}
```

**Comment by HashemKhalifa** [comment]
@visualcookie Thank you so much! 
The issue I'm currently facing is after creating the translation I can access it from the API normally for example.
```javascript
{
	share_campaign{
    data{
      translation {
        language_code
        title,
        subtitle
      }
      domain{
        name
      }
      title
      subtitle    
}
    
  }
}
```

and with gatsby, I couldn't find the `translations` object in the response. 
`        "message": "Cannot query field \"translation\" on type \"DirectusShareCampaign\".",`

**Comment by visualcookie** [comment]
@HashemKhalifa Have you checked the GraphiQL interface, that's provided with Gatsby if the translations are in there?

**Comment by HashemKhalifa** [comment]
@visualcookie yes, not even there!
I can get only from the `DirectusShareCampaignTranslation` for example but I couldn't find it in the GraphQl interface.

I followed the docs but I'm not sure if I missed something!

**Comment by HashemKhalifa** [comment]
@visualcookie the problem is `GSD7: warning Could not find an Many-To-One match in 'share_campaign' for item in 'share_campaign_translations'`

**Comment by visualcookie** [comment]
@HashemKhalifa Hm, actually can't help you there. Maybe the author can help, but I don't know if he's still actively pursuing this source plugin.

**Comment by HashemKhalifa** [comment]
@visualcookie thanks a lot, I will try to create a pull request with the fix

**Comment by Jonesus** [comment]
Hi @HashemKhalifa and @visualcookie !

Sorry for the long silence, I've been quite busy with other stuff recently. As for the issue, a new official plugin has been created at https://github.com/directus/gatsby-source, and thus this project won't be maintained anymore. You should go try it out instead and see if it works out for you and if not, open a new issue in that repo :)
