### ISSUE TITLE
authenticate via static token.

### ISSUE THREAD

**Issue by JulyTheMonth** [Jonesus/gatsby-source-directus7#17]
Hey.

Is there a way to authenticate with a static token instead of the credentials?

As it is possible in the original version by iKonrad.

**Comment by Jonesus** [comment]
Hello @JulyTheMonth ! Thanks for bringing this up, it has been on my to-do list for a while, I'll try to implement it in a release during this week :)

**Comment by Jonesus** [comment]
Hi @JulyTheMonth !

Sorry for the long silence, I've been quite busy with other stuff recently. As for the issue, a new official plugin has been created at https://github.com/directus/gatsby-source, and thus this project won't be maintained anymore. It seems to have the token authentication already implemented, so I hope it works out for you :)
