### ISSUE TITLE
childImageSharp no longer working on images

### ISSUE THREAD

**Issue by Steven-Harris** [Jonesus/gatsby-source-directus7#19]
here is an example: https://github.com/Steven-Harris/gatsby-starter-default-directus-issue
error: Could not find field type. DirectusFile.childImageSharp

**Comment by Jonesus** [comment]
Hi @Steven-Harris!

Sorry for the long silence, I've been quite busy with other stuff recently. As for the issue, a new official plugin has been created at https://github.com/directus/gatsby-source, and thus this project won't be maintained anymore. You should go try it out instead and see if it works out for you and if not, open a new issue in that repo :)
