### ISSUE TITLE
many to many relations

### ISSUE THREAD

**Issue by paolodedomini** [Jonesus/gatsby-source-directus7#21]
hi, there's  way to deal with m2m? it seems that, beside the terminal that say:
`GSD7: info Status matched for progetti_strumenti 1. Using item
GSD7: info Status matched for progetti_strumenti 2. Using item
GSD7: info Status matched for strumenti 1. Using item
GSD7: info Status matched for test 1. Using item
GSD7: info Fetching Directus Relations data...
GSD7: success Retrieved all data from Directus!
GSD7: info Directus data processing starting...
GSD7: info Mapping Directus relations to Items...
GSD7: info Found Many-To-Many relation: strumenti <-> Progetti`

there's no way to find the relation strumenti <-> Progetti in graphql. It's just not there.

Any idea?
thanks

**Comment by paolodedomini** [comment]
It also seem just not deal whit any junction collection... in graphql i cannot access to any of them

**Comment by Jonesus** [comment]
Hi @paolodedomini!

Sorry for the long silence, I've been quite busy with other stuff recently. As for the issue, a new official plugin has been created at https://github.com/directus/gatsby-source, and thus this project won't be maintained anymore. You should go try it out instead and see if it works out for you and if not, open a new issue in that repo :)
