### ISSUE TITLE
Bug mapping relations - TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by jaksm** [Jonesus/gatsby-source-directus7#8]
Everything works fine in directus but when I run gatsby develop I get this error:

`success open and validate gatsby-configs — 0.008 s
success load plugins — 0.211 s
success onPreInit — 0.007 s
success initialize cache — 0.012 s
success copy gatsby files — 0.024 s
success onPreBootstrap — 0.015 s
⠁ gatsby-source-directus info Directus Data Fetcher initializing...
gatsby-source-directus success Connected to Directus!
gatsby-source-directus success Logged in to Directus!
gatsby-source-directus info Fetching Directus file data...
⡀ source and transform nodesgatsby-source-directus success Found 14 files from Directus.
gatsby-source-directus info Downloading Directus files to Gatsby build cache...
Downloading remote files [==============================] 14/14 0.1 secs 100%
gatsby-source-directus success Downloaded all 14 files from Directus!
gatsby-source-directus info Fetching Directus Collection data...
⠐ source and transform nodesgatsby-source-directus info Fetching Directus Items data...
⠂ source and transform nodesgatsby-source-directus info Fetching Directus Relations data...
⡀ source and transform nodesgatsby-source-directus info Mapping Directus relations to Items...
gatsby-source-directus info Found One-To-Many relation: customer -> categories
error Plugin gatsby-source-directus7 returned an error

  TypeError: Cannot read property 'filter' of undefined
  
  - process.js:171 mappedEntities.(anonymous function).mappedEntities.(anonymous function).map.entity
    [nuvitek-website]/[gatsby-source-directus7]/process.js:171:46
  
  - Array.map
  
  - process.js:170 relations.forEach.relation
    [nuvitek-website]/[gatsby-source-directus7]/process.js:170:47
  
  - Array.forEach
  
  - process.js:145 mapRelations
    [nuvitek-website]/[gatsby-source-directus7]/process.js:145:13
  
  - gatsby-node.js:70 Object.exports.sourceNodes
    [nuvitek-website]/[gatsby-source-directus7]/gatsby-node.js:70:60
  
  - task_queues.js:86 processTicksAndRejections
    internal/process/task_queues.js:86:5
  

success source and transform nodes — 1.309 s
success building schema — 0.367 s
success createPages — 0.001 s
success createPagesStatefully — 0.069 s
success onPreExtractQueries — 0.000 s
success update schema — 0.054 s
success extract queries from components — 0.026 s
success run graphql queries — 0.010 s — 2/2 201.65 queries/second
success write out page data — 0.005 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 4.047730672 s

 DONE  Compiled successfully in 2083ms                                                                                                                                    5:38:53 PM

You can now view gatsby-starter-hello-world in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use npm run build

ℹ ｢wdm｣: 
ℹ ｢wdm｣: Compiled successfully.`

There are a few more one-to-many relations in my database, but only this fails, what can I do to fix this?

**Comment by Jonesus** [comment]
Interesting, could you give me a database dump of the problematic project so I could try to reproduce the bug?
`mysqldump -u [username] -p[password] [databaseName] > [filename].sql`

**Comment by Jonesus** [comment]
Hi @jaksm ! Sorry for coming back to this issue after such a long time, I've pushed a few releases since this issue and now the latest [v0.8.0](https://github.com/Jonesus/gatsby-source-directus7/releases/tag/v0.8.0) release should at least be working :) Please open a new issue or reopen this one if the problems still persist!
